
<h1 class="page-header">Categories</h1>
<div class="col-sm-offset-1 ">
    <?= $this->form; ?>
</div>
<br><hr><br>
<div class="col-sm-offset-1">
	<table class=" table table-bordered table-hover">
	<tr>
		<th>Categories</th>
		<th colspan="2">Actions</th>
	</tr>
	<?php
		foreach ($this->categories as $category) 
		{
	?>
			<tr>
				<td><?=$category['name']?></td>
				<td class="success"><a href="<?=$this->baseUrl()?>/categories/edit/id/<?=$category['id']?>">UPDATE</a></td>
				<td class="danger"><a href="<?=$this->baseUrl()?>/categories/delete/id/<?=$category['id']?>">DELETE</a></td>
			</tr>
	<?php   				
		}
	?>
	</table>
</div>
	