
<link rel="stylesheet" type="text/css" href="<?=$this->baseUrl()?>/css/bootstrap.css">


<!-- Custom CSS -->
    <link href="<?=$this->baseUrl()?>/css/sb-admin.css" rel="stylesheet">

    <!-- Morris Charts CSS -->
    <link href="<?=$this->baseUrl()?>/css/morris.css" rel="stylesheet">

<br /><br />
<div id="view-content">
	<!-- <p>View script for controller <b>Requests</b> and script/action name <b>index</b></p> -->
	<h2> <b> List all requests :  <b> </h2>
</div>

<?php

	echo "<a href='".$this->baseUrl()."/requests/list'> list all unread requests </a><br>";
	foreach ($this->requests as $req)
	{
		if($req['is_read'] == 0)
		{
			$mark = "Read ";
		}
		else
		{
			$mark = "Unread";
		}


		
	// echo "<label> <b> ID: </b> </label>".$req['id'].'<br />';
	echo "<label> <b> RequestContent : </b> </label><br>".$req['content'].'<br />';

	
	echo "<a href='".$this->baseUrl()."/requests/delete/id/".$req['id']."'> Delete </a> "."<a href='".$this->baseUrl()."/requests/mark/id/".$req['id']."'> ".$mark."</a> <br />";

	// echo "<label> <b> User: </b> </label>".$req['user_id'].'<br />';
	// echo "<label> <b> From : </b> </label>";
	// foreach ($this->uname as  $value) 
	// 	{
	// 		echo $value;
	// 	}
	
	echo "<hr>";
	
		
	}
	// var_dump($this->uname);
	// echo "<h3> New Request</h3>";
	// echo "<a href='".$this->baseUrl()."/requests/add/'> NewRequest </a>";

?>


<script src="<?=$this->baseUrl()?>/js/jquery.js"></script>
    <script src="<?=$this->baseUrl()?>/js/raphael.min.js"></script>
    <script src="<?=$this->baseUrl()?>/js/morris.min.js"></script>
    <script src="<?=$this->baseUrl()?>/js/morris-data.js"></script>