<?php
	// foreach ($this->comments as $comment){
	// echo "<label> ID: </label>".$comment['id'].'<br />';
	// echo "<label> text: </label>".$comment['text'].'<br />';
	// echo "<a href='".$this->baseUrl()."/comments/edit/id/".$comment['id']."'> Edit </a> "."<a href='".$this->baseUrl()."/comments/delete/id/".$comment['id']."'> Delete </a> <br />";
	// echo str_repeat('*', 100).'<br />';
	// }
echo "hello maaterials";

?>