<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/bootstrap.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/font-awesome.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/templatemo_style.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/templatemo_misc.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/flexslider.css">
<link rel="stylesheet" href="<?=$this->baseUrl()?>/css/testimonails-slider.css">
<script src="<?=$this->baseUrl()?>/js/vendor/modernizr-2.6.1-respond-1.1.0.min.js"></script>

<h2>SIngle Material</h2>
<div id="product-post">
    	<div class="container">
			<div class="row">
		        <div class="col-md-12">
		            <div class="col-sm-offset-1">
		            <?php
						foreach ($this->material as $material){
		               	echo"<h1>". $material['name']."</h1>";
		               	echo "<h1>".$material['description']."</h1>";
		                }
		                if ($this->material['is_download']=1) {
		                	echo"<div class='row'>
                       			 <div class='col-md-6 col-sm-4'>";
						echo "<a class='btn btn-success' href='".$this->baseUrl()."/material/download'> Download </a>";
						}
						echo "<a class='btn btn-primary' href='".$this->baseUrl()."/material/view/id/".$material['id']."'> View </a> ";
						echo "</div></div>";
		               ?>
		            </div>
		        </div>

		        <!-- comments -->
		        

<?php       
		   
echo "<h3>Comments</h3>";
foreach ($this->comment as $comments){
	echo "<label> text: </label>".$comments['content'].' publish at'.$comments['publish_date'].'</br>';
	echo "<a href='".$this->baseUrl()."/comments/edit/id/".$comments['id']."'> Edit </a> "."<a href='".$this->baseUrl()."/comments/delete/id/".$comments['id']."'> Delete </a> <br />";

}
echo"<h2>Add Comment</h2>";
echo $this->form;

?>

<script src="<?=$this->baseUrl()?>/js/jquery-1.11.0.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/jquery.gmap3.min.js"></script>
<script src="<?=$this->baseUrl()?>/js/plugins.js"></script>
<script src="<?=$this->baseUrl()?>/js/main.js"></script>
	