<br /><br />
<div id="view-content">
	<p>View script for controller <b>Material</b> and script/action name <b>video</b></p>
</div>

<div style="text-align:center"> 
  <button onclick="playPause()">Play/Pause</button> 
  <button onclick="makeBig()">Big</button>
  <button onclick="makeSmall()">Small</button>
  <button onclick="makeNormal()">Normal</button>
  <br><br>
  <video id="video1" width="420" controls autoplay src="<?php echo $this->video ?>">
    <!--<source src="<?php echo $this->video ?>" type="video/mp4">-->

  </video>
</div> 
<?php echo $this->video ;?>
<script> 
var myVideo = document.getElementById("video1"); 

function playPause() { 
    if (myVideo.paused) 
        myVideo.play(); 
    else 
        myVideo.pause(); 
} 

function makeBig() { 
    myVideo.width = 560; 
} 

function makeSmall() { 
    myVideo.width = 320; 
} 

function makeNormal() { 
    myVideo.width = 420; 
} 
</script>