
   		
<h1 class="page-header">Courses</h1>
<div class="col-sm-offset-1 ">
    <?= $this->form; ?>
</div>
<br><hr><br>
<div class="col-sm-offset-1">
	<table class=" table table-bordered table-hover">
	<tr>
		<th>Courses</th>
		<th colspan="2">Actions</th>
	</tr>
	<?php
		foreach ($this->courses as $course) 
		{
	?>
			<tr>
				<td><?=$course['name']?></td>
				<td class="success"><a href="<?=$this->baseUrl()?>/courses/edit/cId/<?=$course['id']?>">UPDATE</a></td>
				<td class="danger"><a href="<?=$this->baseUrl()?>/courses/delete/cId/<?=$course['id']?>">DELETE</a></td>
			</tr>
	<?php   				
		}
	?>
	</table>
</div>
	
